[package]
name = "open_links"
version = "0.1.0"
authors = ["Andrew Rondeau <github@andrewrondeau.com>"]
edition = "2018"

[dependencies]
webbrowser = "0.5.5"
tide = "0.14.0"
async-std = { version = "1.7.0", features = ["attributes"] }
futures = "0.3.7"